language: ruby
cache: bundler
rvm:
- 2.4
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
before_deploy:
- git config --local user.name "YOUR GIT USER NAME"
- git config --local user.email "YOUR GIT USER EMAIL"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
- echo -e "\n\n\nbefore_deploy\n\n\n"
deploy:
  provider: releases
  api_key:
    secure: XxZp846a+JEpFUBq/GNCvhe3uR+nmJj4+ZhLxDOcJ0795/7tdC9g9MdMy6eIoXBCv5YLn3jqn8RfGylJZD8hW1SYEOwfU3N4JFQxlKlTdHreEp3VqIIVwUv0WHYA0pEDkJzhcxiI+uzqy0Qth/YVKHPR51BUAGKlQpa2g9jfa9ku8CCRODxvRpgCuHFZ5FUp6+jRY7I5hMTLkHmqan48s/EPtKKxRtdtgWIOBCMVQCRGzHZLcXnbR6n5crIqVQkECj/E8WjlabnrZlkmwB+5v9PIXLRcs3WzQB3LxpCZE1SNLnOnkkZ6sFwr2Z3Dumb9groz77ihgT8SEDjaoxyH/bT7uWZdcX3/OH+jGC1eNYHvnXtrHVcuQrAedg9kMJj/q6WRRDpym4F4bJFPdLAgjoVw6XhOf6zc20G3RQlrVPQHwdwPAWL1D8gBSWCkt78yNUe2duWVMHkTaJBgbhFjJwfkhw7eI5qFY8gjgLOhEvfeoin4x7WPoFflTJoOIo+2pe6OcaKMG0DAsXtt+lXwapmoGmE+cF7ClLHDWKEBgDUC/onVH/Yq3/elSQ0kd3e/QtLcyDTHs+lbMjelr6t5qycXp5KiC1v29fTLyibN8bOhILtFmmbxmfg6XA5iiJCYn9CcxdJQwLeGWkn5gPfx46hWPVmxBz1lNSaqe3E8+uo=
  file_glob: true
  file: "/home/travis/build/bootladder/blog/jekyll/_site.zip"
  skip_cleanup: true
  script: echo -e "\n\n\ndeploy\n\n\n"
  on:
    repo: bootladder/blog
    branch: master
