#!/bin/bash

cd /tmp
wget https://github.com/elm/compiler/releases/download/0.19.0/binaries-for-linux.tar.gz
tar zvxf binaries-for-linux.tar.gz
cd -
cd jekyll/elm
/tmp/elm make src/Main.elm src/SelectorVisual.elm --output elmapp.js && mv elmapp.js ../assets/
ls ../assets
cd -
rm /tmp/elm

echo cd jekyll
cd jekyll

echo zipping the site
zip -r sitesource.zip *
mv sitesource.zip /tmp/
ls
echo assets: 
ls assets

echo curling the site
#curl -F 'file=@/tmp/sitesource.zip' http://freejekyllbuilder.com/upload/bootladder-blog
curl -F 'file=@/tmp/sitesource.zip' http://45.77.4.146:9004/upload/bootladder-blog
sleep 2

echo triggering prod webhook
curl https://ccram.org:5000/bootladder-blog

